import { seed, topic, type TopicSpec } from "@/lib/question-bank-spec";

export const ML_AI_TOPIC_SPECS: TopicSpec[] = [
  topic(
    "supervised-learning-generalization",
    "Supervised Learning & Generalization",
    "Today’s drill focuses on labels, hypothesis classes, overfitting, and the generalization ideas that separate a trained model from a trustworthy one.",
    {
      easy: [
        seed(
          "supervised-data-shape",
          "supervised learning",
          "training from labeled examples",
          "Supervised learning fits a mapping from inputs to targets using examples where the desired output is already known.",
          [
            "Supervised learning only applies when the model is a neural network.",
            "Supervised learning means the model invents its own labels during deployment.",
            "Supervised learning is any training run that uses gradient descent.",
          ],
          "The defining feature of supervised learning is labeled input-output pairs. Architecture and optimizer choices are secondary.",
        ),
        seed(
          "classification-vs-regression",
          "the difference between classification and regression",
          "choosing a prediction task",
          "Classification predicts discrete categories, while regression predicts continuous numeric values.",
          [
            "Classification predicts larger datasets, while regression predicts smaller ones.",
            "Classification is for neural nets, while regression is for linear models.",
            "Classification predicts exact labels and regression predicts probabilities only.",
          ],
          "The target type matters most: categories imply classification; continuous quantities imply regression.",
        ),
        seed(
          "training-validation-test",
          "training, validation, and test splits",
          "splitting a labeled dataset",
          "Training data fits parameters, validation data tunes choices, and test data estimates final generalization after decisions are locked.",
          [
            "Validation data is only for computing gradients, while test data is for feature engineering.",
            "Test data should be reused during model selection so comparisons are fair.",
            "Training and validation can be merged before any experimentation because they play the same role.",
          ],
          "The split roles are different by design. Validation helps choose; test provides the final unbiased check after those choices are made.",
        ),
        seed(
          "overfitting-core",
          "overfitting",
          "a model that memorizes quirks of the training set",
          "Overfitting happens when a model captures noise or dataset-specific patterns that do not generalize to new data.",
          [
            "Overfitting means the model trained too slowly, so it never learned the signal.",
            "Overfitting only occurs when the dataset contains mislabeled examples.",
            "Overfitting means the training loss and test loss are guaranteed to be identical.",
          ],
          "A model can fit training data extremely well while still failing on fresh data. That gap is the operational risk of overfitting.",
        ),
        seed(
          "underfitting-core",
          "underfitting",
          "a model that misses the main structure in the data",
          "Underfitting means the model is too weak, too constrained, or too poorly trained to capture even the training-set signal.",
          [
            "Underfitting means the model memorized the training set perfectly.",
            "Underfitting only refers to bad validation metrics, not training behavior.",
            "Underfitting disappears automatically whenever the dataset is large.",
          ],
          "If the model cannot explain the training data well enough, it is still below the problem’s complexity, regardless of dataset size.",
        ),
        seed(
          "bias-variance-intuition",
          "the bias-variance tradeoff",
          "reasoning about model complexity",
          "Higher-capacity models can reduce bias but often increase variance, so better fit on one dataset can come with less stable generalization.",
          [
            "Bias and variance are interchangeable names for training and test accuracy.",
            "Variance decreases whenever a model adds more parameters and therefore more flexibility.",
            "Bias-variance tradeoff only matters for linear regression and not for modern ML.",
          ],
          "Bias is systematic misspecification; variance is sensitivity to data fluctuations. Model capacity and data size move these risks differently.",
        ),
        seed(
          "feature-label-leakage",
          "data leakage",
          "building features from information unavailable at prediction time",
          "Leakage occurs when training features contain future or target-correlated information that would not exist in the real deployment setting.",
          [
            "Leakage just means the dataset has duplicate rows.",
            "Leakage is any situation where the model performs poorly on the training set.",
            "Leakage only matters when the labels are manually annotated.",
          ],
          "Leakage makes offline evaluation look unrealistically strong by giving the model information it will never legitimately have in production.",
        ),
        seed(
          "baseline-model-purpose",
          "why to build a baseline model",
          "starting a new supervised learning project",
          "A baseline gives a reference point so you can tell whether added complexity actually improves performance over a simple standard.",
          [
            "A baseline is only useful after deep models have already been trained.",
            "A baseline exists mainly to maximize leaderboard scores as quickly as possible.",
            "A baseline should be skipped when the project has many features.",
          ],
          "Good engineering starts with a simple benchmark. Without that anchor, model complexity can look impressive without being useful.",
        ),
        seed(
          "class-imbalance-intuition",
          "class imbalance",
          "predicting a rare event",
          "Class imbalance means some labels are much rarer than others, so naive accuracy can hide failure on the minority class.",
          [
            "Class imbalance means the training set is too small for any classifier.",
            "Class imbalance disappears as long as the model outputs probabilities.",
            "Class imbalance only matters for regression problems.",
          ],
          "When one class dominates, a trivial model can appear accurate while missing the cases you care about most.",
        ),
        seed(
          "generalization-definition",
          "generalization",
          "evaluating a trained model on unseen data",
          "Generalization is the model’s ability to perform well on new samples drawn from the same target distribution, not just the training set.",
          [
            "Generalization means the model can memorize all training rows with zero loss.",
            "Generalization means the model architecture can be reused across unrelated tasks without retraining.",
            "Generalization is the same thing as convergence speed during optimization.",
          ],
          "A model is valuable because it transfers beyond the specific examples it saw. Strong training performance alone is not the goal.",
        ),
      ],
      medium: [
        seed(
          "distribution-shift-risk",
          "distribution shift",
          "shipping a model trained on one population into a meaningfully different environment",
          "Distribution shift breaks the assumption that future inputs resemble training data, so offline metrics can overstate real-world performance.",
          [
            "Distribution shift only matters when labels are missing at inference time.",
            "Distribution shift is solved automatically once the training loss reaches zero.",
            "Distribution shift is just another name for gradient noise during optimization.",
          ],
          "Supervised learning assumes train and deployment data are related. When that assumption breaks, the evaluation contract breaks too.",
        ),
        seed(
          "cross-validation-purpose",
          "cross-validation",
          "estimating performance when a dataset is limited",
          "Cross-validation rotates train-validation partitions so performance estimates rely less on any single split and better reflect sample variability.",
          [
            "Cross-validation replaces the need for a final holdout test set in every workflow.",
            "Cross-validation means training once and evaluating on progressively larger batches.",
            "Cross-validation is only valid for neural networks because they need many passes over data.",
          ],
          "Multiple folds reduce split luck. It is a robustness technique for model selection and estimation, not a free pass to reuse test data.",
        ),
        seed(
          "regularization-generalization",
          "regularization",
          "trying to reduce overfitting in a high-capacity model",
          "Regularization constrains the effective model or learning dynamics so the model fits signal without relying as heavily on fragile patterns.",
          [
            "Regularization is only useful when the training loss is already high.",
            "Regularization means adding more layers so the optimizer has more options.",
            "Regularization guarantees zero train-test gap as long as the penalty term is large enough.",
          ],
          "The point of regularization is not simply to make weights smaller. It is to steer the learner toward solutions that are more stable and more likely to generalize.",
        ),
        seed(
          "label-noise-consequence",
          "label noise",
          "training with inconsistent or partially incorrect targets",
          "Label noise caps the quality the model can learn because the target itself becomes unreliable, often increasing variance and depressing achievable accuracy.",
          [
            "Label noise only affects calibration, not classification accuracy.",
            "Label noise can always be ignored if the model has enough parameters.",
            "Label noise helps regularize the model by making the task harder in a beneficial way.",
          ],
          "The model is optimized against the labels it sees. If those labels are corrupted, the learner gets conflicting supervision.",
        ),
        seed(
          "dataset-representativeness",
          "dataset representativeness",
          "auditing whether a supervised dataset matches the intended users and settings",
          "A representative dataset covers the population and operating conditions the model will actually face, rather than a narrow convenience sample.",
          [
            "A representative dataset is any dataset large enough to fill GPU memory.",
            "Representativeness only matters for fairness and not for overall model quality.",
            "Representativeness is guaranteed if the labels were collected carefully.",
          ],
          "Sampling quality affects the validity of the entire training-and-evaluation loop. A clean but narrow dataset can still mislead deployment decisions.",
        ),
      ],
      hard: [
        seed(
          "erm-limit",
          "empirical risk minimization",
          "minimizing loss on the observed dataset",
          "Empirical risk minimization optimizes performance on sampled data, but generalization still depends on hypothesis capacity, data quality, and how well the sample matches deployment.",
          [
            "Empirical risk minimization guarantees optimal test performance as soon as training loss is minimized.",
            "Empirical risk minimization is invalid unless the training set is perfectly balanced across labels.",
            "Empirical risk minimization only applies to convex models and not to deep learning.",
          ],
          "ERM is a training principle, not a proof of deployment reliability. Good generalization requires more than fitting the observed sample well.",
        ),
        seed(
          "selection-bias-evaluation",
          "selection bias in supervised evaluation",
          "benchmarking a model on data gathered from an easier or filtered subset of users",
          "If the evaluation set is biased toward easier or atypical examples, the reported metric estimates performance on that subset rather than on the real target population.",
          [
            "Selection bias only matters when the dataset size is too small for significance testing.",
            "Selection bias changes the runtime cost of the model but not the validity of the metric.",
            "Selection bias disappears once labels are manually verified by experts.",
          ],
          "The meaning of a metric depends on the distribution it was measured on. If the sample is systematically filtered, the estimate answers the wrong question.",
        ),
      ],
      expert: [],
    },
  ),
  topic(
    "evaluation-metrics-data-splits",
    "Evaluation, Metrics & Data Splits",
    "Today’s drill is about choosing the right metric, guarding the evaluation protocol, and knowing when a number on a dashboard is actually answering the wrong question.",
    {
      easy: [
        seed(
          "precision-definition",
          "precision",
          "evaluating positive predictions",
          "Precision measures how many predicted positives are actually positive.",
          [
            "Precision measures how many actual positives were found overall.",
            "Precision measures the fraction of all examples that were classified correctly.",
            "Precision measures the average confidence of the model.",
          ],
          "Precision is about the quality of positive predictions. It answers: when the model says positive, how often is it right?",
        ),
        seed(
          "recall-definition",
          "recall",
          "evaluating whether the model finds the positive class",
          "Recall measures how many actual positives the model successfully identifies.",
          [
            "Recall measures how many predicted positives are correct.",
            "Recall measures the fraction of all predictions with high confidence.",
            "Recall measures how stable the model is across random seeds.",
          ],
          "Recall focuses on coverage of the positive class. It answers: of the true positives that existed, how many did the model catch?",
        ),
        seed(
          "accuracy-limit",
          "why accuracy can be misleading",
          "evaluating a rare-event classifier",
          "Accuracy can hide failure on rare but important classes because a model can be mostly correct by predicting the majority label.",
          [
            "Accuracy is misleading only when the dataset has missing values.",
            "Accuracy is misleading because it ignores false positives but counts false negatives twice.",
            "Accuracy is always the best metric whenever the classes are discrete.",
          ],
          "Class balance and business cost matter. A high overall hit rate can still be useless if the errors fall on the cases that matter most.",
        ),
        seed(
          "confusion-matrix-role",
          "a confusion matrix",
          "breaking down classification outcomes",
          "A confusion matrix counts true positives, false positives, true negatives, and false negatives so you can inspect error types directly.",
          [
            "A confusion matrix stores the weights of the final linear layer.",
            "A confusion matrix is a table of feature correlations used before training.",
            "A confusion matrix only applies to regression because errors are continuous.",
          ],
          "The confusion matrix is useful because it separates different mistakes instead of collapsing everything into a single number.",
        ),
        seed(
          "roc-pr-curves",
          "ROC and precision-recall curves",
          "sweeping classification thresholds",
          "These curves show how performance changes as the decision threshold moves, rather than fixing a single cutoff.",
          [
            "ROC and PR curves are used only after training neural networks with batch normalization.",
            "ROC and PR curves replace the need for a validation split.",
            "ROC and PR curves are only meaningful when the classifier predicts hard labels and not scores.",
          ],
          "A score-based classifier supports many operating points. Curves reveal the tradeoff surface instead of hiding it behind one threshold.",
        ),
        seed(
          "holdout-purpose",
          "a holdout set",
          "preserving data for final evaluation",
          "A holdout set is kept out of model selection so it can provide an unbiased final estimate once the system design is fixed.",
          [
            "A holdout set is a backup training set used only when the first run diverges.",
            "A holdout set should be consulted during every hyperparameter tweak for faster iteration.",
            "A holdout set exists mainly to compute gradients on especially difficult examples.",
          ],
          "If you keep using the same data to make choices, you start overfitting to the benchmark itself. A holdout guards against that.",
        ),
        seed(
          "calibration-meaning",
          "calibration",
          "interpreting predicted probabilities",
          "A calibrated model produces probabilities that match observed frequencies, so predictions near 0.8 are correct about 80% of the time in aggregate.",
          [
            "Calibration means the model ranks all positives above all negatives.",
            "Calibration means the model loss decreases monotonically every epoch.",
            "Calibration means predicted probabilities sum to one across the entire dataset.",
          ],
          "Good ranking and good probabilities are different goals. Calibration is about the trustworthiness of the probability values themselves.",
        ),
        seed(
          "threshold-choice",
          "classification thresholding",
          "turning model scores into decisions",
          "The threshold should reflect the cost tradeoff between false positives and false negatives, not just default to 0.5 blindly.",
          [
            "The threshold must always be 0.5 because probabilities above half are mathematically correct decisions.",
            "The threshold is irrelevant as long as the model was trained with cross-entropy.",
            "The threshold should be chosen from the test set so the final accuracy is highest.",
          ],
          "Deployment decisions are economic or operational choices. Thresholds translate model scores into actions, so costs and risk matter.",
        ),
        seed(
          "regression-metric-basics",
          "common regression metrics",
          "measuring numeric prediction error",
          "Metrics like mean absolute error and mean squared error summarize how far predictions deviate from true numeric targets.",
          [
            "Regression is evaluated only with accuracy after continuous targets are binned.",
            "Regression metrics are used only when the model has one feature.",
            "Regression metrics count precision and recall across positive classes.",
          ],
          "Regression needs error measures that respect numeric distance. A miss by 0.1 and a miss by 100 should not be treated the same way by default.",
        ),
        seed(
          "data-snooping-risk",
          "data snooping",
          "repeatedly checking results on the same benchmark during experimentation",
          "Data snooping leaks selection pressure into evaluation, so the reported number can become overly optimistic even without changing the model intentionally.",
          [
            "Data snooping is only a storage bug caused by duplicate rows.",
            "Data snooping helps generalization because the model sees more examples indirectly.",
            "Data snooping only matters when features are standardized incorrectly.",
          ],
          "Repeated comparison against the same benchmark effectively tunes to it. The benchmark stops being a clean test of out-of-sample performance.",
        ),
      ],
      medium: [
        seed(
          "pr-vs-roc-imbalance",
          "choosing between ROC and precision-recall views",
          "evaluating a classifier for a rare positive class",
          "Precision-recall analysis is often more informative under strong class imbalance because it focuses directly on positive-class retrieval quality.",
          [
            "ROC analysis becomes mathematically invalid whenever positives are rare.",
            "Precision-recall analysis should only be used after the model is perfectly calibrated.",
            "The two views are always equivalent as long as the threshold is optimized.",
          ],
          "ROC can still be useful, but when positives are rare, PR often better reflects whether the system finds valuable cases without too many false alarms.",
        ),
        seed(
          "macro-vs-micro-averaging",
          "macro versus micro averaging",
          "evaluating a multiclass or multilabel system",
          "Macro averaging weights classes more evenly, while micro averaging aggregates instance-level decisions and can be dominated by common classes.",
          [
            "Macro and micro averaging differ only in how confidence scores are normalized.",
            "Micro averaging is required whenever the classifier uses softmax outputs.",
            "Macro averaging always gives a higher score than micro averaging on imbalanced data.",
          ],
          "The averaging scheme encodes what you care about: balanced treatment across classes or aggregate performance across all examples.",
        ),
        seed(
          "temporal-split-need",
          "time-aware validation",
          "building a model from chronologically ordered events",
          "When the data has a time axis, validation should respect chronology so the model is evaluated on the future rather than on leaked historical neighbors.",
          [
            "Random shuffling is always safer because it destroys any accidental correlations.",
            "Temporal splits are unnecessary unless the labels themselves are timestamps.",
            "Temporal splits matter only for recurrent networks and not for other models.",
          ],
          "Random splits can let information from the future influence training indirectly. Time-aware evaluation is about preserving the real prediction setting.",
        ),
        seed(
          "metric-alignment-business",
          "metric alignment",
          "choosing an offline score for a production workflow",
          "The right metric should match the decision costs and product objective, not just whichever benchmark score is easiest to improve.",
          [
            "Metric alignment mainly means choosing the metric with the biggest numeric range.",
            "Any differentiable training loss is automatically the right business metric.",
            "Metric alignment only matters after deployment because offline evaluation is purely technical.",
          ],
          "A model can improve the wrong metric and still harm the product. Evaluation needs to reflect what the system is actually trying to optimize.",
        ),
        seed(
          "calibration-vs-discrimination",
          "calibration versus discrimination",
          "auditing a probabilistic classifier",
          "A model can rank examples well yet produce poorly calibrated probabilities, because ordering quality and probability accuracy are separate properties.",
          [
            "A model with good calibration must also have perfect ranking by definition.",
            "Calibration and discrimination differ only for regression, not for classification.",
            "A model cannot be miscalibrated once it uses logistic loss during training.",
          ],
          "Ranking tells you who is more likely than whom. Calibration tells you whether the stated probabilities mean what they say.",
        ),
      ],
      hard: [
        seed(
          "offline-online-gap",
          "the gap between offline metrics and online impact",
          "shipping a recommender or ranking model based on benchmark improvement alone",
          "Offline gains do not guarantee product gains because user behavior, feedback loops, latency, and intervention costs can change the effective objective after deployment.",
          [
            "Offline gains always translate directly online if the metric was computed on enough data.",
            "Offline and online metrics differ only when the model is underfitting.",
            "An online experiment is unnecessary once the holdout set is large enough.",
          ],
          "Real systems interact with users and policies. A static benchmark cannot fully capture those downstream effects.",
        ),
        seed(
          "group-metric-audit",
          "subgroup performance auditing",
          "checking a classifier that serves multiple user populations",
          "Aggregate metrics can conceal failures on specific groups, so evaluation should often be broken down by subgroup rather than reported only as one global average.",
          [
            "Subgroup metrics are unnecessary if the overall validation set is large.",
            "Subgroup audits matter only for legal compliance and not for technical quality.",
            "A single threshold guarantees equal performance across groups whenever the model is calibrated.",
          ],
          "Different populations can experience different error rates, calibration, or coverage even when the global score looks strong.",
        ),
      ],
      expert: [],
    },
  ),
  topic(
    "optimization-regularization-training",
    "Optimization, Regularization & Training Dynamics",
    "Today’s drill is about loss landscapes, learning-rate discipline, and the optimization choices that decide whether a model learns useful structure or just thrashes.",
    {
      easy: [
        seed(
          "gradient-descent-core",
          "gradient descent",
          "updating model parameters with respect to a loss",
          "Gradient descent moves parameters in the direction that most decreases loss locally, which is the negative gradient direction.",
          [
            "Gradient descent adds the gradient so the loss increases toward a sharper optimum.",
            "Gradient descent only works when there are no nonlinear activations.",
            "Gradient descent guarantees the global optimum for every modern neural network.",
          ],
          "The gradient points uphill in loss. Optimization steps move against that direction to reduce the objective locally.",
        ),
        seed(
          "learning-rate-role",
          "the learning rate",
          "choosing the step size for optimization",
          "The learning rate controls how large each parameter update is, so it affects both convergence speed and stability.",
          [
            "The learning rate decides how many training examples belong in the dataset.",
            "The learning rate measures model capacity rather than update size.",
            "The learning rate only matters on the first optimization step.",
          ],
          "Too small can be painfully slow; too large can destabilize training. Step size is one of the highest-leverage optimization choices.",
        ),
        seed(
          "batch-size-basic",
          "batch size",
          "computing a stochastic gradient step",
          "Batch size is the number of training examples used to estimate the gradient for one parameter update.",
          [
            "Batch size is the number of model layers updated per epoch.",
            "Batch size is the number of classes in the label space.",
            "Batch size is the total number of optimizer steps in the run.",
          ],
          "Mini-batch training uses a sample of examples to estimate the full-data gradient, balancing compute efficiency and noise.",
        ),
        seed(
          "epoch-meaning",
          "an epoch",
          "describing training progress",
          "An epoch is one full pass through the training dataset, though the exact number of updates depends on batch size.",
          [
            "An epoch is one parameter in the model after optimization.",
            "An epoch is one validation run regardless of how much training happened.",
            "An epoch is the number of hidden units in a layer.",
          ],
          "Epochs describe coverage of the dataset, not the optimization algorithm itself.",
        ),
        seed(
          "regularization-l2",
          "L2 regularization",
          "penalizing large weights during training",
          "L2 regularization adds a penalty on weight magnitude, encouraging smaller parameters and often smoother, less brittle solutions.",
          [
            "L2 regularization deletes random training examples each epoch.",
            "L2 regularization forces all weights to be exactly zero after convergence.",
            "L2 regularization only changes inference speed and not generalization.",
          ],
          "An L2 penalty nudges the optimizer away from excessively large weights, which can improve stability and generalization in many settings.",
        ),
        seed(
          "dropout-basic",
          "dropout",
          "regularizing a neural network during training",
          "Dropout randomly masks units during training so the network does not rely too heavily on one fragile pattern or co-adaptation path.",
          [
            "Dropout permanently removes neurons from the architecture after each epoch.",
            "Dropout is a preprocessing step for missing-value imputation.",
            "Dropout guarantees the highest possible training accuracy by reducing noise.",
          ],
          "Dropout injects stochasticity during training to make the learned representation more robust.",
        ),
        seed(
          "early-stopping-intuition",
          "early stopping",
          "monitoring validation performance during training",
          "Early stopping halts training when validation quality stops improving, limiting overfitting from continuing to optimize the training objective alone.",
          [
            "Early stopping means ending training as soon as the training loss reaches zero.",
            "Early stopping is only for unsupervised learning and not for predictive models.",
            "Early stopping replaces the need for a validation set entirely.",
          ],
          "Past a certain point, extra optimization can improve training fit while worsening generalization. Early stopping uses validation as the stop signal.",
        ),
        seed(
          "optimizer-momentum",
          "momentum in optimization",
          "accelerating gradient-based training",
          "Momentum accumulates a running direction from past gradients so optimization can move more smoothly through noisy or curved regions.",
          [
            "Momentum randomly restarts the optimizer whenever loss plateaus.",
            "Momentum freezes old gradients so only the latest batch matters.",
            "Momentum is another name for gradient clipping.",
          ],
          "Momentum uses history to damp oscillations and preserve useful directional progress.",
        ),
        seed(
          "normalization-benefit",
          "feature normalization",
          "preparing numeric inputs for optimization",
          "Normalization puts features on more comparable scales, which often makes optimization more stable and easier to tune.",
          [
            "Normalization guarantees better test accuracy because all features become equally important.",
            "Normalization is only needed when the model has exactly one hidden layer.",
            "Normalization removes all outliers by definition.",
          ],
          "Poor feature scaling can distort the geometry seen by the optimizer. Comparable scales often improve conditioning and training behavior.",
        ),
        seed(
          "loss-function-role",
          "a loss function",
          "training a predictive model",
          "The loss function quantifies how wrong predictions are, giving optimization a target to minimize.",
          [
            "The loss function stores the labels so the model can retrieve them later.",
            "The loss function is the same thing as the optimizer hyperparameters.",
            "The loss function only matters after training when you report metrics.",
          ],
          "Without a loss, there is no explicit objective telling the model what counts as a better or worse prediction during training.",
        ),
      ],
      medium: [
        seed(
          "learning-rate-too-high",
          "an overly large learning rate",
          "debugging unstable training curves",
          "If the learning rate is too high, optimization can overshoot useful regions, causing divergence, oscillation, or highly erratic loss.",
          [
            "A too-large learning rate only slows convergence but cannot destabilize it.",
            "A too-large learning rate is harmless once momentum is enabled.",
            "A too-large learning rate affects validation loss only and not training loss.",
          ],
          "Step size directly controls update magnitude. Large steps can hop across valleys instead of descending into them.",
        ),
        seed(
          "learning-rate-too-low",
          "an overly small learning rate",
          "training that barely improves after many steps",
          "If the learning rate is too low, optimization can make progress so slowly that training appears stuck even when the direction is reasonable.",
          [
            "A too-small learning rate causes overfitting by default because it regularizes too little.",
            "A too-small learning rate guarantees the global optimum if training runs long enough.",
            "A too-small learning rate only matters for batch size, not for parameter updates.",
          ],
          "Stable but tiny updates can still be a practical failure if they do not reach a good region in the available compute budget.",
        ),
        seed(
          "train-val-loss-gap",
          "interpreting training and validation curves together",
          "seeing training loss continue down while validation loss rises",
          "That pattern often indicates overfitting: the model keeps fitting training specifics while generalization degrades.",
          [
            "That pattern proves the validation set is mislabeled.",
            "That pattern means the optimizer has stopped updating parameters entirely.",
            "That pattern is expected whenever the model uses stochastic mini-batches and does not signal anything about generalization.",
          ],
          "The key issue is divergence between fitting the training set and performing on held-out data. Validation is the guardrail for that gap.",
        ),
        seed(
          "weight-decay-vs-data-augmentation",
          "different regularization mechanisms",
          "comparing weight decay and data augmentation",
          "Both can improve generalization, but weight decay constrains parameters directly while augmentation changes the effective training distribution by adding invariant-preserving examples.",
          [
            "They are identical because both simply add Gaussian noise to gradients.",
            "Only one of them counts as regularization because the other changes the dataset.",
            "They differ only in runtime speed and not in what they encourage the model to learn.",
          ],
          "Regularization can act through the objective, architecture, optimization path, or data distribution. These tools operate through different channels.",
        ),
        seed(
          "gradient-noise-mini-batch",
          "stochastic gradient noise",
          "using mini-batches instead of the full dataset",
          "Mini-batch gradients are noisy estimates of the full-data gradient, which can help exploration but also make optimization less smooth.",
          [
            "Mini-batch gradients are exact replicas of full-batch gradients as long as the batch is shuffled.",
            "Gradient noise only appears after the model begins overfitting.",
            "Stochastic gradients are noisy because labels are randomized during training.",
          ],
          "Sampling fewer examples per step trades exactness for speed. That stochasticity becomes part of the training dynamics.",
        ),
      ],
      hard: [
        seed(
          "conditioning-and-optimization",
          "optimization conditioning",
          "training a model whose objective is stretched very differently across parameter directions",
          "Poor conditioning makes some directions much steeper than others, so one global learning rate struggles to move efficiently without instability.",
          [
            "Poor conditioning only affects memory usage and not optimization behavior.",
            "Poor conditioning disappears automatically if the model is deep enough.",
            "Poor conditioning means the loss function has multiple labels instead of one.",
          ],
          "Conditioning is about geometry. When curvature varies strongly across directions, optimization becomes harder to tune and slower to converge.",
        ),
        seed(
          "implicit-regularization-optimization",
          "implicit regularization",
          "comparing two optimizers that fit the training set similarly but generalize differently",
          "Optimization choices can bias which zero-training-error solution is found, so the training path itself can affect generalization even with the same objective.",
          [
            "If two models reach the same training loss, they must generalize identically by definition.",
            "Implicit regularization only exists when explicit penalties like L2 are absent from the codebase.",
            "Optimization path matters only for linear algebra efficiency and not for the learned function.",
          ],
          "The loss surface can contain many solutions with similar training error. Optimizer dynamics influence which one you actually land on.",
        ),
      ],
      expert: [],
    },
  ),
  topic(
    "neural-networks-representation-learning",
    "Neural Networks & Representation Learning",
    "Today’s drill is about distributed representations, activation flow, and the mechanisms that let neural models turn raw inputs into useful internal features.",
    {
      easy: [
        seed(
          "neuron-computation",
          "what a basic neural unit computes",
          "passing an input through a learned layer",
          "A neural unit applies a weighted combination of inputs plus bias, then usually passes the result through a nonlinear activation.",
          [
            "A neural unit sorts the input features and chooses the median value.",
            "A neural unit stores the entire dataset inside one parameter vector.",
            "A neural unit only performs useful computation when the output layer is recurrent.",
          ],
          "The basic building block is affine transformation plus optional nonlinearity. Stacking many such units gives expressive function approximators.",
        ),
        seed(
          "activation-function-purpose",
          "why activation functions matter",
          "building a multi-layer neural network",
          "Nonlinear activations let stacked layers represent functions more expressive than a single linear transformation.",
          [
            "Activations mainly reduce memory usage by clipping tensors to smaller ranges.",
            "Activations are optional because stacking linear layers is already nonlinear in depth.",
            "Activations exist only to make gradients larger in every layer.",
          ],
          "Without nonlinearity, multiple linear layers collapse into one linear map. Activations create the expressive gain of depth.",
        ),
        seed(
          "embedding-intuition",
          "an embedding",
          "representing tokens or items in a vector space",
          "An embedding maps discrete entities into dense vectors so similarity and downstream learning can operate in a continuous space.",
          [
            "An embedding is a sparse one-hot vector with no learned parameters.",
            "An embedding is the same thing as the raw text prompt passed to a model.",
            "An embedding only exists in recommender systems and not in language models.",
          ],
          "Embeddings convert symbolic inputs into learned geometry. Nearby vectors can encode useful semantic or structural relations.",
        ),
        seed(
          "hidden-layer-purpose",
          "hidden layers",
          "learning intermediate features before the final prediction",
          "Hidden layers transform raw inputs into intermediate representations that can make the final task easier to solve.",
          [
            "Hidden layers are only for storing gradients until backpropagation ends.",
            "Hidden layers are required only when the dataset is unlabeled.",
            "Hidden layers remove the need for an output layer because they can directly emit labels.",
          ],
          "Representation learning is the key idea: the network builds features useful for the prediction objective rather than relying only on hand-engineered ones.",
        ),
        seed(
          "backprop-high-level",
          "backpropagation",
          "training a neural network end to end",
          "Backpropagation efficiently computes gradients by applying the chain rule backward through the computation graph.",
          [
            "Backpropagation reorders the training data from easiest to hardest each epoch.",
            "Backpropagation only works when the network has exactly two layers.",
            "Backpropagation is the same thing as dropout because both operate during training.",
          ],
          "The core win of backprop is computational reuse. It makes training large networks feasible by sharing intermediate derivative calculations.",
        ),
        seed(
          "relu-basic",
          "ReLU activation",
          "choosing a common nonlinearity",
          "ReLU outputs zero for negative inputs and the input itself for positive inputs, making it simple and widely used in deep nets.",
          [
            "ReLU outputs a probability distribution over classes.",
            "ReLU is a normalization method that rescales features to zero mean.",
            "ReLU guarantees no gradients ever vanish in deep networks.",
          ],
          "ReLU is popular because it is simple and often easier to optimize than saturating nonlinearities, though it still has failure modes.",
        ),
        seed(
          "softmax-purpose",
          "softmax",
          "producing multiclass output scores",
          "Softmax converts logits into a normalized distribution over classes so the outputs can be interpreted relative to one another.",
          [
            "Softmax sorts logits from largest to smallest but keeps their original values.",
            "Softmax is the hidden-layer nonlinearity that creates embeddings.",
            "Softmax only works for binary classification and not for multiclass tasks.",
          ],
          "Softmax turns arbitrary class scores into positive values that sum to one, which is useful for multiclass probabilistic output layers.",
        ),
        seed(
          "cnn-intuition",
          "why convolution is useful in vision",
          "processing an image with repeated local patterns",
          "Convolution exploits local structure and weight sharing so the model can detect similar features across spatial positions efficiently.",
          [
            "Convolution is useful mainly because it removes all spatial information from images.",
            "Convolution guarantees translation invariance even before training.",
            "Convolution is just matrix multiplication with no structural assumptions at all.",
          ],
          "Weight sharing encodes the idea that similar local features can matter in many locations, which is a strong inductive bias for images.",
        ),
        seed(
          "attention-basic",
          "attention",
          "letting a model weigh different input positions differently",
          "Attention allows the model to compute context-dependent interactions so each token can focus on other relevant tokens.",
          [
            "Attention means the model permanently memorizes every previous batch.",
            "Attention is a regularization trick that randomly drops tokens.",
            "Attention replaces embeddings entirely because tokens no longer need vector representations.",
          ],
          "Attention is powerful because it creates adaptive connectivity: what matters can change from one example and one position to the next.",
        ),
        seed(
          "representation-learning-goal",
          "representation learning",
          "training a network beyond raw feature engineering",
          "Representation learning means the model learns internal features that are useful for the task instead of relying only on fixed handcrafted ones.",
          [
            "Representation learning means compressing the dataset until it fits in GPU memory.",
            "Representation learning only matters for unsupervised objectives and not for classifiers.",
            "Representation learning means every hidden layer must have the same width.",
          ],
          "A major advantage of neural networks is that useful abstractions can emerge inside the model rather than being manually specified in advance.",
        ),
      ],
      medium: [
        seed(
          "vanishing-gradient-intuition",
          "vanishing gradients",
          "training a deep network whose early layers barely update",
          "Vanishing gradients mean error signals shrink as they propagate backward, making early layers learn very slowly or not at all.",
          [
            "Vanishing gradients mean the optimizer step size is too large and the model diverges instantly.",
            "Vanishing gradients only happen in output layers because they see the labels directly.",
            "Vanishing gradients are caused by using too many training examples per epoch.",
          ],
          "Depth helps expressivity, but it also makes gradient propagation harder. Weak error signals can stall learning in earlier layers.",
        ),
        seed(
          "embedding-similarity-use",
          "using embeddings for retrieval or similarity",
          "ranking items by semantic closeness",
          "Embeddings are useful because geometric proximity in vector space can capture learned semantic or behavioral similarity.",
          [
            "Embeddings are useful only because they reduce the number of classes the model must predict.",
            "Embeddings guarantee Euclidean distance matches every human notion of meaning exactly.",
            "Embeddings are retrieval-specific and cannot help classification or recommendation tasks.",
          ],
          "The learned space is valuable when its geometry aligns enough with task structure that nearest neighbors and similarity comparisons become meaningful.",
        ),
        seed(
          "pretraining-finetuning",
          "pretraining followed by fine-tuning",
          "adapting a foundation model to a narrower task",
          "Pretraining learns broad representations from large-scale data, while fine-tuning adjusts those representations to a more specific downstream objective.",
          [
            "Fine-tuning discards the pretrained weights and restarts from random initialization with a smaller learning rate.",
            "Pretraining and fine-tuning are identical except for dataset size.",
            "Fine-tuning is only valid when the downstream labels exactly match the pretraining tokens.",
          ],
          "Large-scale pretraining amortizes feature learning. Fine-tuning specializes that prior rather than relearning everything from scratch.",
        ),
        seed(
          "attention-vs-convolution",
          "attention versus convolution",
          "comparing two architectural inductive biases",
          "Convolution builds in locality and weight sharing, while attention allows flexible content-dependent interactions across positions.",
          [
            "Attention and convolution are mathematically identical except for parameter count.",
            "Attention can only model local context, while convolution captures arbitrary long-range dependencies by default.",
            "Convolution is a training trick and attention is an evaluation metric.",
          ],
          "The main difference is structural bias: convolution assumes repeated local patterns; attention learns dynamic pairwise relevance more directly.",
        ),
        seed(
          "representation-transfer",
          "feature transfer from pretrained models",
          "reusing a backbone learned on a large source task",
          "Transfer works when pretrained representations capture structure useful for the new task, reducing the amount of task-specific data needed.",
          [
            "Transfer only works if the source and target labels are identical.",
            "Transfer guarantees improvement on every target task regardless of domain mismatch.",
            "Transfer means freezing all layers forever so the new task cannot change them.",
          ],
          "Pretrained models encode reusable patterns, but transfer quality still depends on how aligned the source representation is with the target problem.",
        ),
      ],
      hard: [
        seed(
          "attention-context-window-limit",
          "the practical limit of a context window",
          "reasoning about why a model can still fail despite nominally fitting all tokens in context",
          "A larger context window increases accessible information, but usefulness still depends on retrieval quality, attention allocation, and whether the model can actually use the relevant evidence effectively.",
          [
            "If the full document fits in context, the model is guaranteed to use the correct evidence perfectly.",
            "Context windows only affect runtime cost and not reasoning quality.",
            "Context limits disappear completely once embeddings are learned during pretraining.",
          ],
          "Capacity to ingest tokens is not the same as reliable reasoning over them. Utilization and salience still matter.",
        ),
        seed(
          "distributed-representation-benefit",
          "distributed representations",
          "comparing learned neural features to one-hot symbolic encodings",
          "Distributed representations let many concepts share statistical strength across dimensions, enabling compositional similarity and more data-efficient generalization than isolated one-hot features.",
          [
            "Distributed representations are mainly useful because they make gradients unnecessary during training.",
            "Distributed representations prevent different concepts from sharing any parameters, which improves interpretability.",
            "One-hot features always generalize better because every concept is perfectly separated from every other concept.",
          ],
          "When information is spread across shared dimensions, the model can reuse structure across related entities instead of learning each symbol independently.",
        ),
      ],
      expert: [],
    },
  ),
  topic(
    "llms-rag-agentic-systems",
    "LLMs, Embeddings, RAG & Agentic Systems",
    "Today’s drill focuses on foundation-model inference, retrieval quality, hallucination control, and the system boundaries that decide whether an AI feature is trustworthy in production.",
    {
      easy: [
        seed(
          "llm-next-token",
          "what a language model predicts",
          "running an autoregressive model on text",
          "An autoregressive language model predicts the next token distribution conditioned on the tokens seen so far.",
          [
            "A language model predicts the final answer in one step without intermediate token probabilities.",
            "A language model predicts only whether the input text is grammatically correct.",
            "A language model directly emits embeddings instead of token probabilities.",
          ],
          "The standard causal LM objective is next-token prediction. Longer answers emerge by repeating that step autoregressively.",
        ),
        seed(
          "tokenization-basic",
          "tokenization",
          "preparing text for an LLM",
          "Tokenization converts raw text into model-consumable units, which are often subwords rather than whole words or characters.",
          [
            "Tokenization means translating text into a single embedding before the model runs.",
            "Tokenization is only needed for multilingual models and not for English ones.",
            "Tokenization guarantees each word maps to exactly one token.",
          ],
          "LLMs operate on token sequences, not raw strings. The token boundaries depend on the model’s vocabulary and encoding scheme.",
        ),
        seed(
          "context-window-basic",
          "a context window",
          "feeding prompts and retrieved passages into an LLM",
          "The context window is the amount of tokenized information the model can condition on at once during inference.",
          [
            "The context window is the number of training examples used in one epoch.",
            "The context window is the number of model layers that attend to each other.",
            "The context window is only a latency setting and not a limit on available input.",
          ],
          "Context length constrains how much prompt, conversation history, and retrieved evidence can be included in one model invocation.",
        ),
        seed(
          "rag-basic",
          "retrieval-augmented generation",
          "answering a question with external documents",
          "RAG retrieves relevant context from a knowledge source and includes it in the prompt so generation can ground itself in external evidence.",
          [
            "RAG fine-tunes the base model weights every time a new document arrives.",
            "RAG means the model ignores its prompt and reads directly from the database at decoding time.",
            "RAG is only useful when the base model has never seen any text during pretraining.",
          ],
          "RAG is a systems pattern: retrieval supplies fresh or domain-specific evidence without retraining the whole model.",
        ),
        seed(
          "hallucination-basic",
          "hallucination",
          "an LLM producing confident but unsupported content",
          "A hallucination is an output that sounds plausible but is not grounded in reliable evidence or correct reasoning.",
          [
            "A hallucination is any answer shorter than the expected response length.",
            "A hallucination means the model used sampling instead of greedy decoding.",
            "A hallucination only happens when the retrieved context is empty.",
          ],
          "Fluent language is not the same thing as factual correctness. Hallucination is a grounding and reliability problem.",
        ),
        seed(
          "embedding-retrieval-use",
          "why embeddings help retrieval",
          "finding semantically related passages for a query",
          "Embeddings enable semantic retrieval by mapping queries and documents into a shared vector space where related meaning can lie near each other.",
          [
            "Embeddings help retrieval mainly by alphabetizing the documents more efficiently.",
            "Embeddings replace the need for any document chunking or indexing strategy.",
            "Embeddings are only for training and cannot be used during inference pipelines.",
          ],
          "Vector retrieval is powerful because matching can depend on meaning rather than exact lexical overlap alone.",
        ),
        seed(
          "tool-use-basic",
          "tool use in an AI system",
          "letting a model call a calculator or API",
          "Tool use lets the model delegate specific operations to external systems rather than forcing all computation to happen inside the language model itself.",
          [
            "Tool use means the model edits its own weights during each conversation.",
            "Tool use is just another name for prompt templating with no external execution.",
            "Tool use removes the need for input validation because the model decides everything.",
          ],
          "External tools are valuable when a task needs exact computation, fresh data, or privileged side effects beyond text prediction.",
        ),
        seed(
          "agent-loop-basic",
          "an agent loop",
          "iteratively planning, acting, and observing",
          "An agent loop repeatedly reasons about the state, takes an action such as a tool call, observes the result, and decides what to do next.",
          [
            "An agent loop means the model trains online on every user request.",
            "An agent loop is a one-shot prompt with no intermediate state changes.",
            "An agent loop only exists when multiple foundation models are ensembled together.",
          ],
          "What makes an agent system different is the closed loop: the model can act, inspect outcomes, and continue from updated state.",
        ),
        seed(
          "temperature-basic",
          "temperature in decoding",
          "sampling outputs from a language model",
          "Temperature changes how concentrated or spread out the next-token distribution is during sampling, affecting output diversity.",
          [
            "Temperature changes the model weights so it learns new facts at inference time.",
            "Temperature only affects prompt length and not the generated text distribution.",
            "Temperature guarantees factual accuracy whenever it is set to zero.",
          ],
          "Decoding settings change sampling behavior, not the trained knowledge inside the model. Lower temperature usually makes outputs more deterministic.",
        ),
        seed(
          "prompt-instructions-role",
          "prompt instructions",
          "steering a foundation model for a task",
          "Prompt instructions shape the task framing and constraints presented to the model, but they do not replace grounding, evaluation, or system safeguards.",
          [
            "Prompt instructions permanently retrain the model for all future users.",
            "Prompt instructions guarantee truthful answers if they are written formally enough.",
            "Prompt instructions only matter for chat interfaces and not for API calls.",
          ],
          "Prompting is important, but it is not magic. Strong systems combine prompt design with retrieval, tools, validation, and monitoring.",
        ),
      ],
      medium: [
        seed(
          "chunking-tradeoff",
          "document chunking in RAG",
          "preparing a knowledge base for retrieval",
          "Chunk size trades precision against context coverage: chunks that are too small can lose coherence, while chunks that are too large can dilute relevance and waste context window budget.",
          [
            "Chunking only affects storage cost and not retrieval quality.",
            "The best chunk size is always the largest one that fits in the model context window.",
            "Chunking is unnecessary once embeddings are normalized to unit length.",
          ],
          "RAG quality depends heavily on how evidence is packaged before retrieval. Chunking influences both what gets retrieved and what the model can use.",
        ),
        seed(
          "retrieval-vs-generation-failure",
          "separating retrieval failures from generation failures",
          "debugging a RAG system that answers incorrectly",
          "You should first check whether the right evidence was retrieved; if not, the issue is upstream of generation rather than just a prompting problem.",
          [
            "Any wrong answer proves the base model needs fine-tuning and retrieval is irrelevant.",
            "If the output is fluent, retrieval must have succeeded and the problem is only evaluation.",
            "Retrieval and generation failures cannot be separated because they are the same subsystem.",
          ],
          "A RAG system is a pipeline. Debugging requires knowing whether the model failed to find evidence or failed to use evidence it already had.",
        ),
        seed(
          "grounded-citations-value",
          "why to surface citations or evidence spans",
          "designing a user-facing assistant for enterprise knowledge",
          "Citations let users inspect the supporting evidence, which improves trust, debugging, and the ability to reject unsupported answers.",
          [
            "Citations mainly reduce token cost because the model no longer needs retrieved documents.",
            "Citations guarantee the cited passage actually supports the generated claim in every case.",
            "Citations are unnecessary once the model is instruction-tuned.",
          ],
          "Evidence visibility does not solve grounding by itself, but it makes the system more auditable and easier to challenge.",
        ),
        seed(
          "agent-state-need",
          "persistent state in an agentic system",
          "building a workflow agent that operates across multiple steps or sessions",
          "Persistent state is needed when future decisions depend on prior observations, tool outputs, or user choices that should survive beyond one prompt.",
          [
            "Persistent state is only for analytics dashboards and not for model behavior.",
            "Persistent state is unnecessary because the model weights already remember previous tool calls.",
            "Persistent state only matters if the system uses reinforcement learning.",
          ],
          "Multi-step systems need memory outside the immediate prompt window if they are to behave coherently across actions and time.",
        ),
        seed(
          "eval-set-for-llm-systems",
          "evaluation for an LLM application",
          "measuring whether a RAG or agent workflow is improving",
          "Useful evaluation often mixes task-specific correctness checks, retrieval quality checks, and operational metrics rather than relying on one generic language score.",
          [
            "Perplexity alone is enough to evaluate any downstream LLM application.",
            "LLM applications cannot be evaluated meaningfully because outputs are open-ended.",
            "If users like the tone of the answer, factual evaluation is unnecessary.",
          ],
          "Application-level quality is multi-component. Retrieval, tool execution, factual grounding, latency, and user outcome can all matter.",
        ),
      ],
      hard: [
        seed(
          "rag-system-contract",
          "the contract of a retrieval-augmented system",
          "deciding what it means for a generated answer to be trustworthy",
          "A trustworthy RAG system needs both evidence retrieval that is relevant and generation that stays faithful to that evidence, because either half can fail independently.",
          [
            "Trustworthiness depends only on the language model if the retriever has high recall.",
            "Trustworthiness depends only on retrieval because generation cannot alter the meaning of provided evidence.",
            "Trustworthiness is guaranteed whenever the system includes more than one retrieved chunk.",
          ],
          "Grounding is an end-to-end property. Good retrieved documents are not enough if the generator misuses them, and good prompting is not enough if evidence is missing.",
        ),
        seed(
          "agent-side-effect-guardrails",
          "guardrails for tool-using agents",
          "letting an agent trigger external side effects such as writes, purchases, or account changes",
          "High-impact agent actions need explicit authorization, validation, and auditable execution boundaries because language-model reasoning alone is not a sufficient safety control.",
          [
            "If the agent explains its plan clearly, additional authorization is redundant.",
            "Guardrails mainly slow the agent down and are only useful for model training diagnostics.",
            "Tool guardrails are unnecessary when the model temperature is set to zero.",
          ],
          "Once an agent can act on real systems, safety becomes a systems-design problem, not just a prompting problem.",
        ),
      ],
      expert: [],
    },
  ),
];
